### PR TITLE
Ftr speedup

### PR DESCRIPTION
**Pull request by bohaohuang**
Added new hdf5 dataset, which avoid scatter file reading for small patch files
Whether to use the old datareader or new hdf5 reader is now determined automatically by the file extension
TODO item: create hdf5 file directly from dataset's raw file

### CODE REVIEW

**Comment by waynehuu** [comment]
@bohaohuang do I need to test this on mnih dataset?

**Comment by bohaohuang** [comment]
> @bohaohuang do I need to test this on mnih dataset?

Yes, please test it. I think it should be fine, but try train w/ .txt patch files, then use _patches_to_hdf5_ in _data/data_utils.py_ to generate .hdf5 format dataset and train with it.
If there's nothing else you think I need to modify, then maybe we can merge it after you tested it on mnih.

**Comment by waynehuu** [comment]
> > @bohaohuang do I need to test this on mnih dataset?
> 
> Yes, please test it. I think it should be fine, but try train w/ .txt patch files, then use _patches_to_hdf5_ in _data/data_utils.py_ to generate .hdf5 format dataset and train with it.
> If there's nothing else you think I need to modify, then maybe we can merge it after you tested it on mnih.

Let's merge this first if it works fine with other datasets. I'll then test it on mnih and build based on it if any incompatability happens. Also I can only pull it after merging.

**Comment by waynehuu** [comment]
Tested on mnih and worked fine.

**Pull request merged**
